version : "3.13"
services:
  app:
    build: .
    volumes :
      - .:/j-awth
    ports:
      [8000:8000]
    image: app:j-awth
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8000