services:
  app:
    build: .
    volumes :
      - .:/j-awth
    ports:
      [8000:8000]
    image: app:j-awth
    container_name: django_container
    command:  python manage.py migrate && python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  db:
    image: postgres
    volumes: 
      - ./data/db:/var/lib/postgresql/data
    environment: 
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgre_db
  # test: 
  #   build: .
  #   command: pytest
  #   volumes: 
  #     - .:/j-awth
  #   environment:
  #     - DB_HOST=db  # DB settings for the test service
  #     - DB_USER=postgres
  #     - DB_PASSWORD=postgres
  #     - DB_NAME=postgres
  #   depends_on:
  #     - app
  #   entrypoint: ["sh", "-c", "sleep 10 && pytest"]
