# Generated by Django 5.1.3 on 2024-11-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='last_login_ip',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='phone_numbers',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
