# Generated by Django 5.1.3 on 2024-11-14 14:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authers', '0002_alter_authuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='phone_numbers',
            field=models.CharField(blank=True, help_text='Enter a indian phone number', max_length=10, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Enter a valid 10-digit Indian phone Number.', regex='^[6-9]\\d{9}$')]),
        ),
    ]
