# Generated by Django 5.1.3 on 2024-11-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authers', '0005_alter_authuser_options_authuser_unique_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
